// Generated by https://quicktype.io
using System;
using Newtonsoft.Json;

namespace datumation_products.Shared.StartupModels {

    public partial class AppConfiguration {
        [JsonProperty ("ConnectionStrings")]
        public ConnectionStrings ConnectionStrings { get; set; }

        [JsonProperty ("LiveReload")]
        public LiveReload LiveReload { get; set; }

        [JsonProperty ("SqlTables")]
        public SqlTables SqlTables { get; set; }

        [JsonProperty ("Logging")]
        public Logging Logging { get; set; }

        [JsonProperty ("Email")]
        public Email Email { get; set; }

        [JsonProperty ("Stripe")]
        public Stripe Stripe { get; set; }

        [JsonProperty ("FileDownloadContentType")]
        public string FileDownloadContentType { get; set; }

        [JsonProperty ("SendGrid")]
        public SendGrid SendGrid { get; set; }

        [JsonProperty ("AzureBlobRootUrl")]
        public Uri AzureBlobRootUrl { get; set; }

        [JsonProperty ("AppRootUrl")]
        public Uri AppRootUrl { get; set; }

        [JsonProperty ("CacheKeys")]
        public CacheKeys CacheKeys { get; set; }

        [JsonProperty ("AllowedHosts")]
        public string AllowedHosts { get; set; }
    }
}