// Generated by https://io
using System.Collections.Generic;
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
namespace datumation_products.Shared.StartupModels {

    public partial class AppSettings {
        [JsonProperty ("AppSettings")]
        public AppConfiguration AppConfiguration { get; set; }
    }

    public partial class AppSettings {
        public static AppSettings FromJson (string json) => JsonConvert.DeserializeObject<AppSettings> (json, Converter.Settings);
    }

    public static class Serialize {
        public static string ToJson (this AppSettings self) => JsonConvert.SerializeObject (self, Converter.Settings);
    }

    internal static class Converter {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters = {
            new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}