// Generated by https://quicktype.io

namespace datumation_products.Shared.StartupModels {
    using Newtonsoft.Json;

    public partial class CacheKeys {
        [JsonProperty ("CacheKeyItemsAll")]
        public string CacheKeyItemsAll { get; set; }

        [JsonProperty ("CacheKeyItemsByStateBase")]
        public string CacheKeyItemsByStateBase { get; set; }

        [JsonProperty ("CacheKeyItemsByTypeBase")]
        public string CacheKeyItemsByTypeBase { get; set; }

        [JsonProperty ("CacheKeyFileDownloadBase")]
        public string CacheKeyFileDownloadBase { get; set; }
    }
}