// Generated by https://quicktype.io

namespace datumation_products.Shared.StartupModels {
    using Newtonsoft.Json;

    public partial class ConnectionStrings {
        [JsonProperty ("DefaultConnection")]
        public string DefaultConnection { get; set; }
    }
}