// Generated by https://quicktype.io

namespace datumation_products.Shared.StartupModels {
    using Newtonsoft.Json;

    public partial class Email {
        [JsonProperty ("Smtp")]
        public Smtp Smtp { get; set; }
    }
}