// Generated by https://quicktype.io

namespace datumation_products.Shared.StartupModels {
    using Newtonsoft.Json;

    public partial class Logging {
        [JsonProperty ("LogLevel")]
        public LogLevel LogLevel { get; set; }
    }
}