// Generated by https://quicktype.io

namespace datumation_products.Shared.StartupModels {
    using Newtonsoft.Json;

    public partial class LogLevel {
        [JsonProperty ("Default")]
        public string Default { get; set; }

        [JsonProperty ("Microsoft")]
        public string Microsoft { get; set; }

        [JsonProperty ("Microsoft.Hosting.Lifetime")]
        public string MicrosoftHostingLifetime { get; set; }
    }
}