// Generated by https://quicktype.io

namespace datumation_products.Shared.StartupModels {
    using Newtonsoft.Json;

    public partial class SendGrid {
        [JsonProperty ("SENDGRID_API_KEY")]
        public string SendgridApiKey { get; set; }
    }
}