// Generated by https://quicktype.io

namespace datumation_products.Shared.StartupModels {
    using Newtonsoft.Json;

    public partial class Smtp {
        [JsonProperty ("Host")]
        public string Host { get; set; }

        [JsonProperty ("Port")]
        public long Port { get; set; }

        [JsonProperty ("Username")]
        public string Username { get; set; }

        [JsonProperty ("Password")]
        public string Password { get; set; }

        [JsonProperty ("ApiKey")]
        public string ApiKey { get; set; }
    }
}