// Generated by https://quicktype.io

namespace datumation_products.Shared.StartupModels {
    using Newtonsoft.Json;

    public partial class SqlTables {
        [JsonProperty ("ItemsTable")]
        public string ItemsTable { get; set; }

        [JsonProperty ("UserOrderDetailsTable")]
        public string UserOrderDetailsTable { get; set; }
    }
}